
# Create GitHub Action Secrets for your version of the application:
#   DEBRICKEN_TOKEN should be an API Access Token from your Debricked tenant.

name: OSS SCA with Debricked

on:
  # Triggers the workflow on push or pull request events but only for the main and develop branches
  push:
    paths:
      - 'package.json'
    branches:
      - '**'        # matches every branch
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runDebrickedScan:
        description: 'Carry out SCA scan using Debricked'
        required: true
        default: 'true'

# Global environment variables
env:
  DEFAULT_APP_NAME: "IWA-ExpressAPI"

jobs:

  Debricked-SCA:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push') || (github.event_name == 'pull_request') || (github.event.inputs.runDebrickedScan == 'true') }}
    steps:
      - uses: actions/checkout@v3
      - uses: debricked/actions@v3
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
